### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shadowTW** [swkeep/keep-oilwell#1]
![image](https://user-images.githubusercontent.com/64441627/168827203-07b7030a-09df-4f02-8bdf-1a2c58edbaa8.png)

**Comment by swkeep** [comment]
Hi, don't worry about this error it happens after every restart/start.
if you want to check whether it's working or not press "o" if the menu came up then it doesn't have a problem.

**Comment by swkeep** [comment]
1. replace "PlayerJob.name == 'oilwell'" in the image with true and check if qbtarget is working or not.
2. in client_lib_entry.lua add a print_table and then check console logs
![print](https://user-images.githubusercontent.com/49286776/168837533-47582528-7b59-4162-afb4-721420d40b38.JPG)

**Comment by swkeep** [comment]
make sure you opened the storage menu once maybe your character doesn't have storage!
I'm gonna add some notifications for some of these errors.

**Comment by swkeep** [comment]
cleanup oilrig_storage/oilrig_CDU/oilrig_Blender in your database maybe something unexpected got through.

**Comment by swkeep** [comment]
extract crude oil with oilwell > pump crude oil to > main storage
main storage >> pump crude oil from main storage to  >> CDU's internal storage

What you are trying to do is pump the oil from storage to CDU storage.

**Comment by swkeep** [comment]
currently, I'm trying to make some sort of queue for load in the truck because if someone tries to spam this function spawn location gonna get exploded by new spawns (just try it :) )
