### ISSUE TITLE
Cant change the color. 

### ISSUE THREAD

**Issue by ShijoDaniel93** [swkeep/keep-oilwell#13]
https://cdn.discordapp.com/attachments/886477166475374634/1015896862684876831/unknown.png

after the qbcore new update. cant change the pet color. what to do???????????

**Comment by GrapsZ** [comment]
Post your problem on the good repository !

**Comment by swkeep** [comment]
@ShijoDaniel93 , I'm going to close this one and create a new one on the keep-companion script, pls.
