### ISSUE TITLE
Sorry, heres my next one :(

### ISSUE THREAD

**Issue by adzboo** [swkeep/keep-oilwell#4]
I dont mean to be a pain with the issues!  it looks like a really indepth job and id like to get it to work

[   script:drp-oiljob] Error loading script @menuv/menuv.lua in resource drp-oiljob: @menuv/menuv.lua:23: assertion failed!
[   script:drp-oiljob] stack traceback:
[   script:drp-oiljob] 	[C]: in function 'assert'
[   script:drp-oiljob] 	@menuv/menuv.lua:23: in main chunk

**Comment by adzboo** [comment]
am i just missing menuv as a resource or something?

**Comment by swkeep** [comment]
it's not so important for script functionality as issue #2. I don't have an exact fix for right now.

**Comment by adzboo** [comment]
tbh, i press O and the menu pops up for rotation and stuff, i just see the error in console and wondered if it was fundamental in the functionality.
