### ISSUE TITLE
Blinking props

### ISSUE THREAD

**Issue by QBLes** [swkeep/keep-oilwell#8]
So i noticed when a user flys in every sprop thats being spawned starts blinking, if i restart the script props are static but if you restart fivem its all on the blink again.

**Comment by QBLes** [comment]
no idea bro, once servers up and running i need to restart script in order for props to spawn..

**Comment by QBLes** [comment]
Ok so i noticed in the updated version you have it does a job check to make sure they have the job, i removed this to look just how you have it and it now works.

This is how your released version looks:

```
if PlayerJob.name == 'oilwell' then
      OnDuty = PlayerData.job.onduty
      loadData()
 end
```

Thanks for the tips bro, 'keep' up the good work

**Comment by swkeep** [comment]
got i fixed job check in my uncommitted version. (it's gonna be a big rework!)

about parts, it might be annoying but i wanted to be players to think about how much they are willing to put in there.
and somewhat scared of using it to hide stuff inside the oil wells.
it was auto removal at first every 10 sec but it was using too much resources.

**Comment by QBLes** [comment]
> got i fixed job check in my uncommitted version. (it's gonna be a big rework!)
> 
> about parts, it might be annoying but i wanted to be players to think about how much they are willing to put in there. and somewhat scared of using it to hide stuff inside the oil wells. it was auto removal at first every 10 sec but it was using too much resources.

oh i see, i never knew this when i first tested it lol, i was like what the hell it took everything, im sure i could code it how i want it i guess, i dont like editing peoples code much, makes it easier to do updates that way lol
